// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base_type.proto

package test_protobuf

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GoBool struct {
	Value                bool     `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoBool) Reset()         { *m = GoBool{} }
func (m *GoBool) String() string { return proto.CompactTextString(m) }
func (*GoBool) ProtoMessage()    {}
func (*GoBool) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{0}
}
func (m *GoBool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoBool.Unmarshal(m, b)
}
func (m *GoBool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoBool.Marshal(b, m, deterministic)
}
func (m *GoBool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoBool.Merge(m, src)
}
func (m *GoBool) XXX_Size() int {
	return xxx_messageInfo_GoBool.Size(m)
}
func (m *GoBool) XXX_DiscardUnknown() {
	xxx_messageInfo_GoBool.DiscardUnknown(m)
}

var xxx_messageInfo_GoBool proto.InternalMessageInfo

func (m *GoBool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type GoInt32 struct {
	Value                int32    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoInt32) Reset()         { *m = GoInt32{} }
func (m *GoInt32) String() string { return proto.CompactTextString(m) }
func (*GoInt32) ProtoMessage()    {}
func (*GoInt32) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{1}
}
func (m *GoInt32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoInt32.Unmarshal(m, b)
}
func (m *GoInt32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoInt32.Marshal(b, m, deterministic)
}
func (m *GoInt32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoInt32.Merge(m, src)
}
func (m *GoInt32) XXX_Size() int {
	return xxx_messageInfo_GoInt32.Size(m)
}
func (m *GoInt32) XXX_DiscardUnknown() {
	xxx_messageInfo_GoInt32.DiscardUnknown(m)
}

var xxx_messageInfo_GoInt32 proto.InternalMessageInfo

func (m *GoInt32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type GoString struct {
	Value                string   `protobuf:"bytes,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoString) Reset()         { *m = GoString{} }
func (m *GoString) String() string { return proto.CompactTextString(m) }
func (*GoString) ProtoMessage()    {}
func (*GoString) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{2}
}
func (m *GoString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoString.Unmarshal(m, b)
}
func (m *GoString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoString.Marshal(b, m, deterministic)
}
func (m *GoString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoString.Merge(m, src)
}
func (m *GoString) XXX_Size() int {
	return xxx_messageInfo_GoString.Size(m)
}
func (m *GoString) XXX_DiscardUnknown() {
	xxx_messageInfo_GoString.DiscardUnknown(m)
}

var xxx_messageInfo_GoString proto.InternalMessageInfo

func (m *GoString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GoBool)(nil), "test_protobuf.GoBool")
	proto.RegisterType((*GoInt32)(nil), "test_protobuf.GoInt32")
	proto.RegisterType((*GoString)(nil), "test_protobuf.GoString")
}

func init() { proto.RegisterFile("base_type.proto", fileDescriptor_97d27fbb7286dd8c) }

var fileDescriptor_97d27fbb7286dd8c = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4f, 0x4a, 0x2c, 0x4e,
	0x8d, 0x2f, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x2d, 0x49, 0x2d,
	0x2e, 0x89, 0x07, 0xb3, 0x93, 0x4a, 0xd3, 0x94, 0xe4, 0xb8, 0xd8, 0xdc, 0xf3, 0x9d, 0xf2, 0xf3,
	0x73, 0x84, 0x44, 0xb8, 0x58, 0xc3, 0x12, 0x73, 0x4a, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x82, 0x20, 0x1c, 0x25, 0x79, 0x2e, 0x76, 0xf7, 0x7c, 0xcf, 0xbc, 0x12, 0x63, 0x23, 0x54, 0x05,
	0xac, 0x30, 0x05, 0x0a, 0x5c, 0x1c, 0xee, 0xf9, 0xc1, 0x25, 0x45, 0x99, 0x79, 0xe9, 0xa8, 0x2a,
	0x38, 0xa1, 0x2a, 0x9c, 0x5c, 0xa2, 0x9c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3,
	0x73, 0xf5, 0x93, 0x33, 0x52, 0x8b, 0x8a, 0x2a, 0x75, 0xd3, 0x13, 0x73, 0x53, 0xa1, 0x6c, 0xfd,
	0xd4, 0x8a, 0xc4, 0xdc, 0x82, 0x9c, 0xd4, 0x62, 0x7d, 0x14, 0xa7, 0x59, 0xa3, 0xf0, 0x92, 0xd8,
	0xc0, 0x2c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x21, 0xbe, 0xb2, 0xd1, 0x00, 0x00,
	0x00,
}
