// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto.proto

package cherryProto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type I32 struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *I32) Reset()         { *m = I32{} }
func (m *I32) String() string { return proto.CompactTextString(m) }
func (*I32) ProtoMessage()    {}
func (*I32) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}
func (m *I32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_I32.Unmarshal(m, b)
}
func (m *I32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_I32.Marshal(b, m, deterministic)
}
func (m *I32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_I32.Merge(m, src)
}
func (m *I32) XXX_Size() int {
	return xxx_messageInfo_I32.Size(m)
}
func (m *I32) XXX_DiscardUnknown() {
	xxx_messageInfo_I32.DiscardUnknown(m)
}

var xxx_messageInfo_I32 proto.InternalMessageInfo

func (m *I32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

// member data
type Member struct {
	NodeId               string            `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeType             string            `protobuf:"bytes,2,opt,name=nodeType,proto3" json:"nodeType,omitempty"`
	Address              string            `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Settings             map[string]string `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Member) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetSettings() map[string]string {
	if m != nil {
		return m.Settings
	}
	return nil
}

// member list data
type MemberList struct {
	List                 []*Member `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberList) Reset()         { *m = MemberList{} }
func (m *MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()    {}
func (*MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}
func (m *MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberList.Unmarshal(m, b)
}
func (m *MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberList.Marshal(b, m, deterministic)
}
func (m *MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberList.Merge(m, src)
}
func (m *MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberList.Size(m)
}
func (m *MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberList proto.InternalMessageInfo

func (m *MemberList) GetList() []*Member {
	if m != nil {
		return m.List
	}
	return nil
}

// cross node response data
type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ClusterPacket struct {
	BuildTime            int64    `protobuf:"varint,1,opt,name=buildTime,proto3" json:"buildTime,omitempty"`
	SourcePath           string   `protobuf:"bytes,2,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"`
	TargetPath           string   `protobuf:"bytes,3,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
	FuncName             string   `protobuf:"bytes,4,opt,name=funcName,proto3" json:"funcName,omitempty"`
	ArgBytes             []byte   `protobuf:"bytes,5,opt,name=argBytes,proto3" json:"argBytes,omitempty"`
	Session              *Session `protobuf:"bytes,6,opt,name=session,proto3" json:"session,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterPacket) Reset()         { *m = ClusterPacket{} }
func (m *ClusterPacket) String() string { return proto.CompactTextString(m) }
func (*ClusterPacket) ProtoMessage()    {}
func (*ClusterPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}
func (m *ClusterPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterPacket.Unmarshal(m, b)
}
func (m *ClusterPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterPacket.Marshal(b, m, deterministic)
}
func (m *ClusterPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterPacket.Merge(m, src)
}
func (m *ClusterPacket) XXX_Size() int {
	return xxx_messageInfo_ClusterPacket.Size(m)
}
func (m *ClusterPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterPacket proto.InternalMessageInfo

func (m *ClusterPacket) GetBuildTime() int64 {
	if m != nil {
		return m.BuildTime
	}
	return 0
}

func (m *ClusterPacket) GetSourcePath() string {
	if m != nil {
		return m.SourcePath
	}
	return ""
}

func (m *ClusterPacket) GetTargetPath() string {
	if m != nil {
		return m.TargetPath
	}
	return ""
}

func (m *ClusterPacket) GetFuncName() string {
	if m != nil {
		return m.FuncName
	}
	return ""
}

func (m *ClusterPacket) GetArgBytes() []byte {
	if m != nil {
		return m.ArgBytes
	}
	return nil
}

func (m *ClusterPacket) GetSession() *Session {
	if m != nil {
		return m.Session
	}
	return nil
}

type Session struct {
	Sid                  string            `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid                  int64             `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	AgentPath            string            `protobuf:"bytes,3,opt,name=agentPath,proto3" json:"agentPath,omitempty"`
	Ip                   string            `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Mid                  uint32            `protobuf:"varint,5,opt,name=mid,proto3" json:"mid,omitempty"`
	Data                 map[string]string `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}
func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *Session) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Session) GetAgentPath() string {
	if m != nil {
		return m.AgentPath
	}
	return ""
}

func (m *Session) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Session) GetMid() uint32 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *Session) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type PomeloResponse struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Mid                  uint32   `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Code                 int32    `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PomeloResponse) Reset()         { *m = PomeloResponse{} }
func (m *PomeloResponse) String() string { return proto.CompactTextString(m) }
func (*PomeloResponse) ProtoMessage()    {}
func (*PomeloResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{6}
}
func (m *PomeloResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PomeloResponse.Unmarshal(m, b)
}
func (m *PomeloResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PomeloResponse.Marshal(b, m, deterministic)
}
func (m *PomeloResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PomeloResponse.Merge(m, src)
}
func (m *PomeloResponse) XXX_Size() int {
	return xxx_messageInfo_PomeloResponse.Size(m)
}
func (m *PomeloResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PomeloResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PomeloResponse proto.InternalMessageInfo

func (m *PomeloResponse) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *PomeloResponse) GetMid() uint32 {
	if m != nil {
		return m.Mid
	}
	return 0
}

func (m *PomeloResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PomeloResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type PomeloPush struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Route                string   `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PomeloPush) Reset()         { *m = PomeloPush{} }
func (m *PomeloPush) String() string { return proto.CompactTextString(m) }
func (*PomeloPush) ProtoMessage()    {}
func (*PomeloPush) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{7}
}
func (m *PomeloPush) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PomeloPush.Unmarshal(m, b)
}
func (m *PomeloPush) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PomeloPush.Marshal(b, m, deterministic)
}
func (m *PomeloPush) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PomeloPush.Merge(m, src)
}
func (m *PomeloPush) XXX_Size() int {
	return xxx_messageInfo_PomeloPush.Size(m)
}
func (m *PomeloPush) XXX_DiscardUnknown() {
	xxx_messageInfo_PomeloPush.DiscardUnknown(m)
}

var xxx_messageInfo_PomeloPush proto.InternalMessageInfo

func (m *PomeloPush) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *PomeloPush) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *PomeloPush) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type PomeloKick struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason               []byte   `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Close                bool     `protobuf:"varint,4,opt,name=close,proto3" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PomeloKick) Reset()         { *m = PomeloKick{} }
func (m *PomeloKick) String() string { return proto.CompactTextString(m) }
func (*PomeloKick) ProtoMessage()    {}
func (*PomeloKick) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{8}
}
func (m *PomeloKick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PomeloKick.Unmarshal(m, b)
}
func (m *PomeloKick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PomeloKick.Marshal(b, m, deterministic)
}
func (m *PomeloKick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PomeloKick.Merge(m, src)
}
func (m *PomeloKick) XXX_Size() int {
	return xxx_messageInfo_PomeloKick.Size(m)
}
func (m *PomeloKick) XXX_DiscardUnknown() {
	xxx_messageInfo_PomeloKick.DiscardUnknown(m)
}

var xxx_messageInfo_PomeloKick proto.InternalMessageInfo

func (m *PomeloKick) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *PomeloKick) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *PomeloKick) GetReason() []byte {
	if m != nil {
		return m.Reason
	}
	return nil
}

func (m *PomeloKick) GetClose() bool {
	if m != nil {
		return m.Close
	}
	return false
}

func init() {
	proto.RegisterType((*I32)(nil), "cherryProto.I32")
	proto.RegisterType((*Member)(nil), "cherryProto.Member")
	proto.RegisterMapType((map[string]string)(nil), "cherryProto.Member.SettingsEntry")
	proto.RegisterType((*MemberList)(nil), "cherryProto.MemberList")
	proto.RegisterType((*Response)(nil), "cherryProto.Response")
	proto.RegisterType((*ClusterPacket)(nil), "cherryProto.ClusterPacket")
	proto.RegisterType((*Session)(nil), "cherryProto.Session")
	proto.RegisterMapType((map[string]string)(nil), "cherryProto.Session.DataEntry")
	proto.RegisterType((*PomeloResponse)(nil), "cherryProto.PomeloResponse")
	proto.RegisterType((*PomeloPush)(nil), "cherryProto.PomeloPush")
	proto.RegisterType((*PomeloKick)(nil), "cherryProto.PomeloKick")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5b, 0x8b, 0xd3, 0x40,
	0x14, 0x26, 0x4d, 0xaf, 0xa7, 0x76, 0x91, 0xb1, 0x2c, 0xa1, 0xca, 0x52, 0xf3, 0x62, 0x5f, 0x4c,
	0xa1, 0x8b, 0x78, 0x29, 0xbe, 0xac, 0x0a, 0x2e, 0x5e, 0x28, 0xd9, 0x7d, 0x12, 0x11, 0xa6, 0xc9,
	0x31, 0x1d, 0x9a, 0x64, 0xca, 0xcc, 0x44, 0xe8, 0xdf, 0x14, 0x7c, 0xf1, 0xd7, 0xc8, 0x5c, 0x92,
	0x76, 0xa1, 0x0f, 0xee, 0x4b, 0x38, 0xdf, 0x77, 0xce, 0x9c, 0xf9, 0xe6, 0x7c, 0x87, 0xc0, 0x70,
	0x27, 0xb8, 0xe2, 0x91, 0xf9, 0x92, 0x61, 0xb2, 0x41, 0x21, 0xf6, 0x2b, 0x0d, 0xc2, 0xc7, 0xe0,
	0x5f, 0x5f, 0x2e, 0xc8, 0x18, 0x3a, 0xbf, 0x68, 0x5e, 0x61, 0xe0, 0x4d, 0xbd, 0x59, 0x27, 0xb6,
	0x20, 0xfc, 0xed, 0x41, 0xf7, 0x0b, 0x16, 0x6b, 0x14, 0xe4, 0x1c, 0xba, 0x25, 0x4f, 0xf1, 0x3a,
	0x35, 0x15, 0x83, 0xd8, 0x21, 0x32, 0x81, 0xbe, 0x8e, 0x6e, 0xf7, 0x3b, 0x0c, 0x5a, 0x26, 0xd3,
	0x60, 0x12, 0x40, 0x8f, 0xa6, 0xa9, 0x40, 0x29, 0x03, 0xdf, 0xa4, 0x6a, 0x48, 0xde, 0x42, 0x5f,
	0xa2, 0x52, 0xac, 0xcc, 0x64, 0xd0, 0x9e, 0xfa, 0xb3, 0xe1, 0xe2, 0x69, 0x74, 0xa4, 0x2a, 0xb2,
	0x97, 0x46, 0x37, 0xae, 0xe6, 0x43, 0xa9, 0xc4, 0x3e, 0x6e, 0x8e, 0x4c, 0x96, 0x30, 0xba, 0x93,
	0x22, 0x0f, 0xc1, 0xdf, 0xe2, 0xde, 0x49, 0xd3, 0xe1, 0xe1, 0x41, 0x56, 0x94, 0x05, 0x6f, 0x5a,
	0xaf, 0xbc, 0xf0, 0x05, 0x80, 0x6d, 0xff, 0x99, 0x49, 0x45, 0x9e, 0x41, 0x3b, 0x67, 0x52, 0x05,
	0x9e, 0x51, 0xf1, 0xe8, 0x84, 0x8a, 0xd8, 0x14, 0x84, 0x0b, 0xe8, 0xc7, 0x28, 0x77, 0xbc, 0x94,
	0x48, 0x08, 0xb4, 0x13, 0x9e, 0xd6, 0xc3, 0x32, 0xb1, 0xe6, 0x52, 0xaa, 0xa8, 0xb9, 0xef, 0x41,
	0x6c, 0xe2, 0xf0, 0x8f, 0x07, 0xa3, 0x77, 0x79, 0x25, 0x15, 0x8a, 0x15, 0x4d, 0xb6, 0xa8, 0xc8,
	0x13, 0x18, 0xac, 0x2b, 0x96, 0xa7, 0xb7, 0xac, 0xb0, 0xc7, 0xfd, 0xf8, 0x40, 0x90, 0x0b, 0x00,
	0xc9, 0x2b, 0x91, 0xe0, 0x8a, 0xaa, 0x8d, 0x53, 0x7e, 0xc4, 0xe8, 0xbc, 0xa2, 0x22, 0x43, 0x65,
	0xf2, 0x76, 0xa6, 0x47, 0x8c, 0x36, 0xe3, 0x67, 0x55, 0x26, 0x5f, 0x69, 0x81, 0x41, 0xdb, 0x9a,
	0x51, 0x63, 0x9d, 0xa3, 0x22, 0xbb, 0xda, 0x2b, 0x94, 0x41, 0xc7, 0x68, 0x6c, 0x30, 0x89, 0xa0,
	0x27, 0x51, 0x4a, 0xc6, 0xcb, 0xa0, 0x3b, 0xf5, 0x66, 0xc3, 0xc5, 0xf8, 0xce, 0x1c, 0x6e, 0x6c,
	0x2e, 0xae, 0x8b, 0xc2, 0xbf, 0x1e, 0xf4, 0x1c, 0xa9, 0x47, 0x2f, 0x59, 0xbd, 0x15, 0x3a, 0xd4,
	0x4c, 0xc5, 0x52, 0x23, 0xdf, 0x8f, 0x75, 0xa8, 0x5f, 0x4d, 0x33, 0x2c, 0x8f, 0x65, 0x1f, 0x08,
	0x72, 0x06, 0x2d, 0xb6, 0x73, 0x7a, 0x5b, 0x6c, 0xa7, 0xcf, 0x17, 0x2c, 0x35, 0x22, 0x47, 0xb1,
	0x0e, 0xc9, 0xc2, 0xcd, 0xb6, 0x67, 0x4c, 0xba, 0x38, 0x25, 0x2e, 0x7a, 0x4f, 0x15, 0xb5, 0x7b,
	0x62, 0x6a, 0x27, 0x2f, 0x61, 0xd0, 0x50, 0xf7, 0xda, 0x8f, 0xef, 0x70, 0xb6, 0xe2, 0x05, 0xe6,
	0xbc, 0xb1, 0xfb, 0xe4, 0x13, 0x0b, 0xf7, 0x44, 0x27, 0xb1, 0xb6, 0xdf, 0x3f, 0xd8, 0xdf, 0xac,
	0x49, 0xfb, 0xb0, 0x26, 0xe1, 0x47, 0x00, 0xdb, 0x7d, 0x55, 0xc9, 0xcd, 0x89, 0xce, 0x63, 0xe8,
	0x08, 0x5e, 0xa9, 0x46, 0x97, 0x01, 0xa7, 0xba, 0x87, 0x3f, 0xea, 0x4e, 0x9f, 0x58, 0xb2, 0xfd,
	0x2f, 0x1b, 0xce, 0xa1, 0x2b, 0x90, 0x4a, 0x5e, 0xba, 0x3e, 0x0e, 0xe9, 0x3b, 0x93, 0x9c, 0x4b,
	0x2b, 0xb4, 0x1f, 0x5b, 0x70, 0xb5, 0xfc, 0xf6, 0x3a, 0x63, 0x6a, 0x53, 0xad, 0xa3, 0x84, 0x17,
	0x73, 0x3b, 0xf2, 0xe7, 0x19, 0x2d, 0xd0, 0xc5, 0xf3, 0x12, 0xd5, 0xdc, 0xfc, 0x51, 0xec, 0x77,
	0x79, 0xe4, 0xca, 0xba, 0x6b, 0xa8, 0xcb, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xac, 0x9d, 0xf2,
	0x2e, 0x79, 0x04, 0x00, 0x00,
}
