// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: proto.proto

package cherryProto

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 成员结构
type Member struct {
	NodeId               string            `protobuf:"bytes,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	NodeType             string            `protobuf:"bytes,2,opt,name=nodeType,proto3" json:"nodeType,omitempty"`
	Address              string            `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Settings             map[string]string `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{0}
}
func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *Member) GetNodeType() string {
	if m != nil {
		return m.NodeType
	}
	return ""
}

func (m *Member) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Member) GetSettings() map[string]string {
	if m != nil {
		return m.Settings
	}
	return nil
}

// 成员列表结构
type MemberList struct {
	List                 []*Member `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MemberList) Reset()         { *m = MemberList{} }
func (m *MemberList) String() string { return proto.CompactTextString(m) }
func (*MemberList) ProtoMessage()    {}
func (*MemberList) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{1}
}
func (m *MemberList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberList.Unmarshal(m, b)
}
func (m *MemberList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberList.Marshal(b, m, deterministic)
}
func (m *MemberList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberList.Merge(m, src)
}
func (m *MemberList) XXX_Size() int {
	return xxx_messageInfo_MemberList.Size(m)
}
func (m *MemberList) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberList.DiscardUnknown(m)
}

var xxx_messageInfo_MemberList proto.InternalMessageInfo

func (m *MemberList) GetList() []*Member {
	if m != nil {
		return m.List
	}
	return nil
}

// 请求消息结构
type Request struct {
	Sid                  string            `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid                  int64             `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	FrontendId           string            `protobuf:"bytes,3,opt,name=frontendId,proto3" json:"frontendId,omitempty"`
	Ip                   string            `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	Setting              map[string]string `protobuf:"bytes,5,rep,name=setting,proto3" json:"setting,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	MsgType              int32             `protobuf:"varint,6,opt,name=msgType,proto3" json:"msgType,omitempty"`
	MsgId                uint32            `protobuf:"varint,7,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Route                string            `protobuf:"bytes,8,opt,name=route,proto3" json:"route,omitempty"`
	Data                 []byte            `protobuf:"bytes,9,opt,name=data,proto3" json:"data,omitempty"`
	IsError              bool              `protobuf:"varint,10,opt,name=isError,proto3" json:"isError,omitempty"`
	Reply                string            `protobuf:"bytes,11,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{2}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *Request) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Request) GetFrontendId() string {
	if m != nil {
		return m.FrontendId
	}
	return ""
}

func (m *Request) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *Request) GetSetting() map[string]string {
	if m != nil {
		return m.Setting
	}
	return nil
}

func (m *Request) GetMsgType() int32 {
	if m != nil {
		return m.MsgType
	}
	return 0
}

func (m *Request) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Request) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Request) GetIsError() bool {
	if m != nil {
		return m.IsError
	}
	return false
}

func (m *Request) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

// 响应消息结构
type Response struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{3}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 推送
type Push struct {
	Route                string   `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	Uid                  int64    `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Push) Reset()         { *m = Push{} }
func (m *Push) String() string { return proto.CompactTextString(m) }
func (*Push) ProtoMessage()    {}
func (*Push) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{4}
}
func (m *Push) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Push.Unmarshal(m, b)
}
func (m *Push) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Push.Marshal(b, m, deterministic)
}
func (m *Push) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Push.Merge(m, src)
}
func (m *Push) XXX_Size() int {
	return xxx_messageInfo_Push.Size(m)
}
func (m *Push) XXX_DiscardUnknown() {
	xxx_messageInfo_Push.DiscardUnknown(m)
}

var xxx_messageInfo_Push proto.InternalMessageInfo

func (m *Push) GetRoute() string {
	if m != nil {
		return m.Route
	}
	return ""
}

func (m *Push) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Push) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// 踢人
type Kick struct {
	Uid                  int64    `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Close                bool     `protobuf:"varint,4,opt,name=close,proto3" json:"close,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Kick) Reset()         { *m = Kick{} }
func (m *Kick) String() string { return proto.CompactTextString(m) }
func (*Kick) ProtoMessage()    {}
func (*Kick) Descriptor() ([]byte, []int) {
	return fileDescriptor_2fcc84b9998d60d8, []int{5}
}
func (m *Kick) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Kick.Unmarshal(m, b)
}
func (m *Kick) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Kick.Marshal(b, m, deterministic)
}
func (m *Kick) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Kick.Merge(m, src)
}
func (m *Kick) XXX_Size() int {
	return xxx_messageInfo_Kick.Size(m)
}
func (m *Kick) XXX_DiscardUnknown() {
	xxx_messageInfo_Kick.DiscardUnknown(m)
}

var xxx_messageInfo_Kick proto.InternalMessageInfo

func (m *Kick) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Kick) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Kick) GetClose() bool {
	if m != nil {
		return m.Close
	}
	return false
}

func init() {
	proto.RegisterType((*Member)(nil), "cherryProto.Member")
	proto.RegisterMapType((map[string]string)(nil), "cherryProto.Member.SettingsEntry")
	proto.RegisterType((*MemberList)(nil), "cherryProto.MemberList")
	proto.RegisterType((*Request)(nil), "cherryProto.Request")
	proto.RegisterMapType((map[string]string)(nil), "cherryProto.Request.SettingEntry")
	proto.RegisterType((*Response)(nil), "cherryProto.Response")
	proto.RegisterType((*Push)(nil), "cherryProto.Push")
	proto.RegisterType((*Kick)(nil), "cherryProto.Kick")
}

func init() { proto.RegisterFile("proto.proto", fileDescriptor_2fcc84b9998d60d8) }

var fileDescriptor_2fcc84b9998d60d8 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0x41, 0x6b, 0xdc, 0x3c,
	0x10, 0x45, 0xb6, 0x77, 0xd7, 0x99, 0x4d, 0x3e, 0x3e, 0xd4, 0x52, 0xc4, 0x1e, 0x8a, 0xbb, 0x97,
	0xfa, 0x52, 0x2f, 0xa4, 0x14, 0xda, 0x2c, 0xbd, 0x04, 0x72, 0x58, 0xda, 0x42, 0x50, 0x7b, 0xea,
	0xcd, 0x6b, 0x4d, 0xbd, 0x22, 0x6b, 0xcb, 0x95, 0xe4, 0x82, 0xff, 0x66, 0x7f, 0x41, 0x7f, 0x4a,
	0x91, 0x6c, 0x6f, 0x1c, 0x92, 0x4b, 0x2f, 0xe6, 0xbd, 0x91, 0x34, 0xef, 0xcd, 0x1b, 0x0c, 0xcb,
	0x46, 0x2b, 0xab, 0x32, 0xff, 0xa5, 0xcb, 0xe2, 0x80, 0x5a, 0x77, 0xb7, 0x8e, 0xac, 0x7f, 0x13,
	0x98, 0x7f, 0xc1, 0x6a, 0x8f, 0x9a, 0xbe, 0x80, 0x79, 0xad, 0x04, 0xee, 0x04, 0x23, 0x09, 0x49,
	0xcf, 0xf8, 0xc0, 0xe8, 0x0a, 0x62, 0x87, 0xbe, 0x75, 0x0d, 0xb2, 0xc0, 0x9f, 0x9c, 0x38, 0x65,
	0xb0, 0xc8, 0x85, 0xd0, 0x68, 0x0c, 0x0b, 0xfd, 0xd1, 0x48, 0xe9, 0x47, 0x88, 0x0d, 0x5a, 0x2b,
	0xeb, 0xd2, 0xb0, 0x28, 0x09, 0xd3, 0xe5, 0xe5, 0xab, 0x6c, 0x22, 0x9c, 0xf5, 0xa2, 0xd9, 0xd7,
	0xe1, 0xce, 0x4d, 0x6d, 0x75, 0xc7, 0x4f, 0x4f, 0x56, 0x5b, 0xb8, 0x78, 0x70, 0x44, 0xff, 0x87,
	0xf0, 0x0e, 0xbb, 0xc1, 0x9a, 0x83, 0xf4, 0x39, 0xcc, 0x7e, 0xe5, 0xc7, 0x76, 0x34, 0xd5, 0x93,
	0xab, 0xe0, 0x3d, 0x59, 0xbf, 0x03, 0xe8, 0xdb, 0x7f, 0x96, 0xc6, 0xd2, 0xd7, 0x10, 0x1d, 0xa5,
	0xb1, 0x8c, 0x78, 0x17, 0xcf, 0x9e, 0x70, 0xc1, 0xfd, 0x85, 0xf5, 0x9f, 0x00, 0x16, 0x1c, 0x7f,
	0xb6, 0x68, 0xac, 0x93, 0x33, 0x72, 0x4c, 0xc2, 0x41, 0x57, 0x69, 0xa5, 0xf0, 0x62, 0x21, 0x77,
	0x90, 0xbe, 0x04, 0xf8, 0xa1, 0x55, 0x6d, 0xb1, 0x16, 0x3b, 0x31, 0xcc, 0x3f, 0xa9, 0xd0, 0xff,
	0x20, 0x90, 0x0d, 0x8b, 0x7c, 0x3d, 0x90, 0x0d, 0xdd, 0xc2, 0x62, 0x98, 0x8f, 0xcd, 0x9e, 0x48,
	0x64, 0x90, 0x1e, 0x23, 0xe9, 0x13, 0x19, 0x5f, 0xb8, 0xa4, 0x2b, 0x53, 0xfa, 0x25, 0xcc, 0x13,
	0x92, 0xce, 0xf8, 0x48, 0x5d, 0x0e, 0x95, 0x29, 0x77, 0x82, 0x2d, 0x12, 0x92, 0x5e, 0xf0, 0x9e,
	0xb8, 0xaa, 0x56, 0xad, 0x45, 0x16, 0xf7, 0xe9, 0x78, 0x42, 0x29, 0x44, 0x22, 0xb7, 0x39, 0x3b,
	0x4b, 0x48, 0x7a, 0xce, 0x3d, 0x76, 0x9d, 0xa5, 0xb9, 0xd1, 0x5a, 0x69, 0x06, 0x09, 0x49, 0x63,
	0x3e, 0x52, 0xdf, 0x03, 0x9b, 0x63, 0xc7, 0x96, 0x43, 0x0f, 0x47, 0x56, 0x57, 0x70, 0x3e, 0xb5,
	0xf8, 0x4f, 0x9b, 0xb9, 0x84, 0x98, 0xa3, 0x69, 0x54, 0x6d, 0xbc, 0x97, 0x42, 0x09, 0xf4, 0x0f,
	0x67, 0xdc, 0xe3, 0x93, 0xbf, 0xe0, 0xde, 0xdf, 0xfa, 0x1a, 0xa2, 0xdb, 0xd6, 0x1c, 0xee, 0x27,
	0x22, 0xd3, 0x89, 0x1e, 0xaf, 0x65, 0xec, 0x11, 0x3e, 0xec, 0xf1, 0x49, 0x16, 0x77, 0xe3, 0x6d,
	0xf2, 0xf8, 0xf6, 0x44, 0xd1, 0x29, 0x15, 0x47, 0x65, 0xd0, 0xef, 0x2e, 0xe6, 0x3d, 0xb9, 0xde,
	0x7e, 0xff, 0x50, 0x4a, 0x7b, 0x68, 0xf7, 0x59, 0xa1, 0xaa, 0x4d, 0xbf, 0xb9, 0x37, 0x65, 0x5e,
	0xe1, 0x80, 0x37, 0x35, 0xda, 0x8d, 0xff, 0xc5, 0xfa, 0xef, 0x76, 0xb2, 0xdc, 0xfd, 0xdc, 0x97,
	0xde, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x24, 0xaa, 0x93, 0x8a, 0x03, 0x00, 0x00,
}
