// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.30.2
// source: proto.proto

package cherryProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PomeloBroadcast_PushType int32

const (
	PomeloBroadcast_AllUID       PomeloBroadcast_PushType = 0 // all agent with uid
	PomeloBroadcast_UID          PomeloBroadcast_PushType = 1 // uidList
	PomeloBroadcast_SessionEqual PomeloBroadcast_PushType = 2 // equal session key
)

// Enum value maps for PomeloBroadcast_PushType.
var (
	PomeloBroadcast_PushType_name = map[int32]string{
		0: "AllUID",
		1: "UID",
		2: "SessionEqual",
	}
	PomeloBroadcast_PushType_value = map[string]int32{
		"AllUID":       0,
		"UID":          1,
		"SessionEqual": 2,
	}
)

func (x PomeloBroadcast_PushType) Enum() *PomeloBroadcast_PushType {
	p := new(PomeloBroadcast_PushType)
	*p = x
	return p
}

func (x PomeloBroadcast_PushType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PomeloBroadcast_PushType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_proto_enumTypes[0].Descriptor()
}

func (PomeloBroadcast_PushType) Type() protoreflect.EnumType {
	return &file_proto_proto_enumTypes[0]
}

func (x PomeloBroadcast_PushType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PomeloBroadcast_PushType.Descriptor instead.
func (PomeloBroadcast_PushType) EnumDescriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{9, 0}
}

type I32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *I32) Reset() {
	*x = I32{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *I32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*I32) ProtoMessage() {}

func (x *I32) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use I32.ProtoReflect.Descriptor instead.
func (*I32) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *I32) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

// member data
type Member struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeID        string                 `protobuf:"bytes,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`                                                                               // node id
	NodeType      string                 `protobuf:"bytes,2,opt,name=nodeType,proto3" json:"nodeType,omitempty"`                                                                           // node type
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`                                                                             // rpc ip address
	Settings      map[string]string      `protobuf:"bytes,4,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // node settings data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Member) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

func (x *Member) GetNodeType() string {
	if x != nil {
		return x.NodeType
	}
	return ""
}

func (x *Member) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Member) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

// member list data
type MemberList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Member              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberList) Reset() {
	*x = MemberList{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberList) ProtoMessage() {}

func (x *MemberList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberList.ProtoReflect.Descriptor instead.
func (*MemberList) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

func (x *MemberList) GetList() []*Member {
	if x != nil {
		return x.List
	}
	return nil
}

// cross node response data
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"` // message code
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`  // message data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClusterPacket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BuildTime     int64                  `protobuf:"varint,1,opt,name=buildTime,proto3" json:"buildTime,omitempty"`
	SourcePath    string                 `protobuf:"bytes,2,opt,name=sourcePath,proto3" json:"sourcePath,omitempty"`
	TargetPath    string                 `protobuf:"bytes,3,opt,name=targetPath,proto3" json:"targetPath,omitempty"`
	FuncName      string                 `protobuf:"bytes,4,opt,name=funcName,proto3" json:"funcName,omitempty"`
	ArgBytes      []byte                 `protobuf:"bytes,5,opt,name=argBytes,proto3" json:"argBytes,omitempty"`
	Session       *Session               `protobuf:"bytes,6,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterPacket) Reset() {
	*x = ClusterPacket{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterPacket) ProtoMessage() {}

func (x *ClusterPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterPacket.ProtoReflect.Descriptor instead.
func (*ClusterPacket) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *ClusterPacket) GetBuildTime() int64 {
	if x != nil {
		return x.BuildTime
	}
	return 0
}

func (x *ClusterPacket) GetSourcePath() string {
	if x != nil {
		return x.SourcePath
	}
	return ""
}

func (x *ClusterPacket) GetTargetPath() string {
	if x != nil {
		return x.TargetPath
	}
	return ""
}

func (x *ClusterPacket) GetFuncName() string {
	if x != nil {
		return x.FuncName
	}
	return ""
}

func (x *ClusterPacket) GetArgBytes() []byte {
	if x != nil {
		return x.ArgBytes
	}
	return nil
}

func (x *ClusterPacket) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`                                                                             // session unique id
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`                                                                            // user id
	AgentPath     string                 `protobuf:"bytes,3,opt,name=agentPath,proto3" json:"agentPath,omitempty"`                                                                 // frontend actor agent path
	Ip            string                 `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`                                                                               // ip address
	Mid           uint32                 `protobuf:"varint,5,opt,name=mid,proto3" json:"mid,omitempty"`                                                                            // message id build by client
	Data          map[string]string      `protobuf:"bytes,7,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // extend data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{5}
}

func (x *Session) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *Session) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Session) GetAgentPath() string {
	if x != nil {
		return x.AgentPath
	}
	return ""
}

func (x *Session) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Session) GetMid() uint32 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *Session) GetData() map[string]string {
	if x != nil {
		return x.Data
	}
	return nil
}

type PomeloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Mid           uint32                 `protobuf:"varint,2,opt,name=mid,proto3" json:"mid,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PomeloResponse) Reset() {
	*x = PomeloResponse{}
	mi := &file_proto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PomeloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PomeloResponse) ProtoMessage() {}

func (x *PomeloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PomeloResponse.ProtoReflect.Descriptor instead.
func (*PomeloResponse) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{6}
}

func (x *PomeloResponse) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *PomeloResponse) GetMid() uint32 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (x *PomeloResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PomeloResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type PomeloPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Route         string                 `protobuf:"bytes,3,opt,name=route,proto3" json:"route,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PomeloPush) Reset() {
	*x = PomeloPush{}
	mi := &file_proto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PomeloPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PomeloPush) ProtoMessage() {}

func (x *PomeloPush) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PomeloPush.ProtoReflect.Descriptor instead.
func (*PomeloPush) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{7}
}

func (x *PomeloPush) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *PomeloPush) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PomeloPush) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *PomeloPush) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PomeloKick struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sid           string                 `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Uid           int64                  `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Reason        []byte                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Close         bool                   `protobuf:"varint,4,opt,name=close,proto3" json:"close,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PomeloKick) Reset() {
	*x = PomeloKick{}
	mi := &file_proto_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PomeloKick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PomeloKick) ProtoMessage() {}

func (x *PomeloKick) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PomeloKick.ProtoReflect.Descriptor instead.
func (*PomeloKick) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{8}
}

func (x *PomeloKick) GetSid() string {
	if x != nil {
		return x.Sid
	}
	return ""
}

func (x *PomeloKick) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PomeloKick) GetReason() []byte {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *PomeloKick) GetClose() bool {
	if x != nil {
		return x.Close
	}
	return false
}

type PomeloBroadcast struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	PushType      PomeloBroadcast_PushType `protobuf:"varint,1,opt,name=pushType,proto3,enum=cherryProto.PomeloBroadcast_PushType" json:"pushType,omitempty"` // boardcast push type
	UidList       []int64                  `protobuf:"varint,2,rep,packed,name=uidList,proto3" json:"uidList,omitempty"`                                      // broadcast the uid list
	SessionKey    string                   `protobuf:"bytes,3,opt,name=sessionKey,proto3" json:"sessionKey,omitempty"`                                        // session key
	SessionValue  string                   `protobuf:"bytes,4,opt,name=sessionValue,proto3" json:"sessionValue,omitempty"`                                    // session value
	Route         string                   `protobuf:"bytes,5,opt,name=route,proto3" json:"route,omitempty"`                                                  // push route
	Data          []byte                   `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`                                                    // push data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PomeloBroadcast) Reset() {
	*x = PomeloBroadcast{}
	mi := &file_proto_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PomeloBroadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PomeloBroadcast) ProtoMessage() {}

func (x *PomeloBroadcast) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PomeloBroadcast.ProtoReflect.Descriptor instead.
func (*PomeloBroadcast) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{9}
}

func (x *PomeloBroadcast) GetPushType() PomeloBroadcast_PushType {
	if x != nil {
		return x.PushType
	}
	return PomeloBroadcast_AllUID
}

func (x *PomeloBroadcast) GetUidList() []int64 {
	if x != nil {
		return x.UidList
	}
	return nil
}

func (x *PomeloBroadcast) GetSessionKey() string {
	if x != nil {
		return x.SessionKey
	}
	return ""
}

func (x *PomeloBroadcast) GetSessionValue() string {
	if x != nil {
		return x.SessionValue
	}
	return ""
}

func (x *PomeloBroadcast) GetRoute() string {
	if x != nil {
		return x.Route
	}
	return ""
}

func (x *PomeloBroadcast) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\x12\vcherryProto\"\x1b\n" +
	"\x03I32\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\"\xd2\x01\n" +
	"\x06Member\x12\x16\n" +
	"\x06nodeID\x18\x01 \x01(\tR\x06nodeID\x12\x1a\n" +
	"\bnodeType\x18\x02 \x01(\tR\bnodeType\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12=\n" +
	"\bsettings\x18\x04 \x03(\v2!.cherryProto.Member.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\n" +
	"MemberList\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.cherryProto.MemberR\x04list\"2\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"\xd5\x01\n" +
	"\rClusterPacket\x12\x1c\n" +
	"\tbuildTime\x18\x01 \x01(\x03R\tbuildTime\x12\x1e\n" +
	"\n" +
	"sourcePath\x18\x02 \x01(\tR\n" +
	"sourcePath\x12\x1e\n" +
	"\n" +
	"targetPath\x18\x03 \x01(\tR\n" +
	"targetPath\x12\x1a\n" +
	"\bfuncName\x18\x04 \x01(\tR\bfuncName\x12\x1a\n" +
	"\bargBytes\x18\x05 \x01(\fR\bargBytes\x12.\n" +
	"\asession\x18\x06 \x01(\v2\x14.cherryProto.SessionR\asession\"\xda\x01\n" +
	"\aSession\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x1c\n" +
	"\tagentPath\x18\x03 \x01(\tR\tagentPath\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x10\n" +
	"\x03mid\x18\x05 \x01(\rR\x03mid\x122\n" +
	"\x04data\x18\a \x03(\v2\x1e.cherryProto.Session.DataEntryR\x04data\x1a7\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\\\n" +
	"\x0ePomeloResponse\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x10\n" +
	"\x03mid\x18\x02 \x01(\rR\x03mid\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\"Z\n" +
	"\n" +
	"PomeloPush\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x14\n" +
	"\x05route\x18\x03 \x01(\tR\x05route\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"^\n" +
	"\n" +
	"PomeloKick\x12\x10\n" +
	"\x03sid\x18\x01 \x01(\tR\x03sid\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x03R\x03uid\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\fR\x06reason\x12\x14\n" +
	"\x05close\x18\x04 \x01(\bR\x05close\"\x8f\x02\n" +
	"\x0fPomeloBroadcast\x12A\n" +
	"\bpushType\x18\x01 \x01(\x0e2%.cherryProto.PomeloBroadcast.PushTypeR\bpushType\x12\x18\n" +
	"\auidList\x18\x02 \x03(\x03R\auidList\x12\x1e\n" +
	"\n" +
	"sessionKey\x18\x03 \x01(\tR\n" +
	"sessionKey\x12\"\n" +
	"\fsessionValue\x18\x04 \x01(\tR\fsessionValue\x12\x14\n" +
	"\x05route\x18\x05 \x01(\tR\x05route\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\"1\n" +
	"\bPushType\x12\n" +
	"\n" +
	"\x06AllUID\x10\x00\x12\a\n" +
	"\x03UID\x10\x01\x12\x10\n" +
	"\fSessionEqual\x10\x02B;Z9github.com/cherry-game/cherry/net/proto/proto;cherryProtob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_proto_goTypes = []any{
	(PomeloBroadcast_PushType)(0), // 0: cherryProto.PomeloBroadcast.PushType
	(*I32)(nil),                   // 1: cherryProto.I32
	(*Member)(nil),                // 2: cherryProto.Member
	(*MemberList)(nil),            // 3: cherryProto.MemberList
	(*Response)(nil),              // 4: cherryProto.Response
	(*ClusterPacket)(nil),         // 5: cherryProto.ClusterPacket
	(*Session)(nil),               // 6: cherryProto.Session
	(*PomeloResponse)(nil),        // 7: cherryProto.PomeloResponse
	(*PomeloPush)(nil),            // 8: cherryProto.PomeloPush
	(*PomeloKick)(nil),            // 9: cherryProto.PomeloKick
	(*PomeloBroadcast)(nil),       // 10: cherryProto.PomeloBroadcast
	nil,                           // 11: cherryProto.Member.SettingsEntry
	nil,                           // 12: cherryProto.Session.DataEntry
}
var file_proto_proto_depIdxs = []int32{
	11, // 0: cherryProto.Member.settings:type_name -> cherryProto.Member.SettingsEntry
	2,  // 1: cherryProto.MemberList.list:type_name -> cherryProto.Member
	6,  // 2: cherryProto.ClusterPacket.session:type_name -> cherryProto.Session
	12, // 3: cherryProto.Session.data:type_name -> cherryProto.Session.DataEntry
	0,  // 4: cherryProto.PomeloBroadcast.pushType:type_name -> cherryProto.PomeloBroadcast.PushType
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		EnumInfos:         file_proto_proto_enumTypes,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
