// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: actor.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

//角色属性变化
type ActorAttribute int32

const (
	ActorAttribute_AA_AttributeNone ActorAttribute = 0
)

var ActorAttribute_name = map[int32]string{
	0: "AA_AttributeNone",
}

var ActorAttribute_value = map[string]int32{
	"AA_AttributeNone": 0,
}

func (x ActorAttribute) String() string {
	return proto.EnumName(ActorAttribute_name, int32(x))
}

func (ActorAttribute) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{0}
}

// 角色基本信息
type Actor struct {
	ActorId              int64    `protobuf:"varint,1,opt,name=actorId,proto3" json:"actorId,omitempty"`
	ActorName            string   `protobuf:"bytes,2,opt,name=actorName,proto3" json:"actorName,omitempty"`
	Gender               int32    `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"`
	ActorLevel           int32    `protobuf:"varint,4,opt,name=actorLevel,proto3" json:"actorLevel,omitempty"`
	CreateTime           int64    `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	ActorExp             int64    `protobuf:"varint,6,opt,name=actorExp,proto3" json:"actorExp,omitempty"`
	HeadIcon             int32    `protobuf:"varint,7,opt,name=headIcon,proto3" json:"headIcon,omitempty"`
	VipLevel             int32    `protobuf:"varint,8,opt,name=vipLevel,proto3" json:"vipLevel,omitempty"`
	FightPower           int64    `protobuf:"varint,9,opt,name=fightPower,proto3" json:"fightPower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Actor) Reset()         { *m = Actor{} }
func (m *Actor) String() string { return proto.CompactTextString(m) }
func (*Actor) ProtoMessage()    {}
func (*Actor) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{0}
}
func (m *Actor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Actor.Unmarshal(m, b)
}
func (m *Actor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Actor.Marshal(b, m, deterministic)
}
func (m *Actor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Actor.Merge(m, src)
}
func (m *Actor) XXX_Size() int {
	return xxx_messageInfo_Actor.Size(m)
}
func (m *Actor) XXX_DiscardUnknown() {
	xxx_messageInfo_Actor.DiscardUnknown(m)
}

var xxx_messageInfo_Actor proto.InternalMessageInfo

func (m *Actor) GetActorId() int64 {
	if m != nil {
		return m.ActorId
	}
	return 0
}

func (m *Actor) GetActorName() string {
	if m != nil {
		return m.ActorName
	}
	return ""
}

func (m *Actor) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *Actor) GetActorLevel() int32 {
	if m != nil {
		return m.ActorLevel
	}
	return 0
}

func (m *Actor) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Actor) GetActorExp() int64 {
	if m != nil {
		return m.ActorExp
	}
	return 0
}

func (m *Actor) GetHeadIcon() int32 {
	if m != nil {
		return m.HeadIcon
	}
	return 0
}

func (m *Actor) GetVipLevel() int32 {
	if m != nil {
		return m.VipLevel
	}
	return 0
}

func (m *Actor) GetFightPower() int64 {
	if m != nil {
		return m.FightPower
	}
	return 0
}

// 查询角色响应
type ActorSelectResponse struct {
	ActorList            []*Actor `protobuf:"bytes,1,rep,name=actorList,proto3" json:"actorList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorSelectResponse) Reset()         { *m = ActorSelectResponse{} }
func (m *ActorSelectResponse) String() string { return proto.CompactTextString(m) }
func (*ActorSelectResponse) ProtoMessage()    {}
func (*ActorSelectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{1}
}
func (m *ActorSelectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorSelectResponse.Unmarshal(m, b)
}
func (m *ActorSelectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorSelectResponse.Marshal(b, m, deterministic)
}
func (m *ActorSelectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorSelectResponse.Merge(m, src)
}
func (m *ActorSelectResponse) XXX_Size() int {
	return xxx_messageInfo_ActorSelectResponse.Size(m)
}
func (m *ActorSelectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorSelectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActorSelectResponse proto.InternalMessageInfo

func (m *ActorSelectResponse) GetActorList() []*Actor {
	if m != nil {
		return m.ActorList
	}
	return nil
}

//请求创建角色
type ActorCreateRequest struct {
	ActorName            string   `protobuf:"bytes,1,opt,name=actorName,proto3" json:"actorName,omitempty"`
	Gender               int32    `protobuf:"varint,2,opt,name=gender,proto3" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorCreateRequest) Reset()         { *m = ActorCreateRequest{} }
func (m *ActorCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ActorCreateRequest) ProtoMessage()    {}
func (*ActorCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{2}
}
func (m *ActorCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorCreateRequest.Unmarshal(m, b)
}
func (m *ActorCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorCreateRequest.Marshal(b, m, deterministic)
}
func (m *ActorCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorCreateRequest.Merge(m, src)
}
func (m *ActorCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ActorCreateRequest.Size(m)
}
func (m *ActorCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ActorCreateRequest proto.InternalMessageInfo

func (m *ActorCreateRequest) GetActorName() string {
	if m != nil {
		return m.ActorName
	}
	return ""
}

func (m *ActorCreateRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

//创建角色回应
type ActorCreateResponse struct {
	ActorInfo            *Actor   `protobuf:"bytes,1,opt,name=actorInfo,proto3" json:"actorInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ActorCreateResponse) Reset()         { *m = ActorCreateResponse{} }
func (m *ActorCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ActorCreateResponse) ProtoMessage()    {}
func (*ActorCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{3}
}
func (m *ActorCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorCreateResponse.Unmarshal(m, b)
}
func (m *ActorCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorCreateResponse.Marshal(b, m, deterministic)
}
func (m *ActorCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorCreateResponse.Merge(m, src)
}
func (m *ActorCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ActorCreateResponse.Size(m)
}
func (m *ActorCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActorCreateResponse proto.InternalMessageInfo

func (m *ActorCreateResponse) GetActorInfo() *Actor {
	if m != nil {
		return m.ActorInfo
	}
	return nil
}

// 进入游戏响应
type ActorEnterResponse struct {
	GuideMaps            map[int32]int32 `protobuf:"bytes,2,rep,name=guideMaps,proto3" json:"guideMaps,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ActorEnterResponse) Reset()         { *m = ActorEnterResponse{} }
func (m *ActorEnterResponse) String() string { return proto.CompactTextString(m) }
func (*ActorEnterResponse) ProtoMessage()    {}
func (*ActorEnterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_93a2698287ded216, []int{4}
}
func (m *ActorEnterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ActorEnterResponse.Unmarshal(m, b)
}
func (m *ActorEnterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ActorEnterResponse.Marshal(b, m, deterministic)
}
func (m *ActorEnterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActorEnterResponse.Merge(m, src)
}
func (m *ActorEnterResponse) XXX_Size() int {
	return xxx_messageInfo_ActorEnterResponse.Size(m)
}
func (m *ActorEnterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ActorEnterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ActorEnterResponse proto.InternalMessageInfo

func (m *ActorEnterResponse) GetGuideMaps() map[int32]int32 {
	if m != nil {
		return m.GuideMaps
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.ActorAttribute", ActorAttribute_name, ActorAttribute_value)
	proto.RegisterType((*Actor)(nil), "pb.Actor")
	proto.RegisterType((*ActorSelectResponse)(nil), "pb.ActorSelectResponse")
	proto.RegisterType((*ActorCreateRequest)(nil), "pb.ActorCreateRequest")
	proto.RegisterType((*ActorCreateResponse)(nil), "pb.ActorCreateResponse")
	proto.RegisterType((*ActorEnterResponse)(nil), "pb.ActorEnterResponse")
	proto.RegisterMapType((map[int32]int32)(nil), "pb.ActorEnterResponse.GuideMapsEntry")
}

func init() { proto.RegisterFile("actor.proto", fileDescriptor_93a2698287ded216) }

var fileDescriptor_93a2698287ded216 = []byte{
	// 387 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xdd, 0x8a, 0xd3, 0x40,
	0x14, 0xc7, 0x9d, 0xc4, 0x74, 0x37, 0x67, 0x61, 0x29, 0xe3, 0x22, 0xc3, 0x22, 0x12, 0x02, 0x6a,
	0xf0, 0x22, 0x82, 0xde, 0x88, 0x88, 0x10, 0x97, 0x22, 0x95, 0x75, 0x91, 0xd1, 0x2b, 0x6f, 0x24,
	0x1f, 0x67, 0xdb, 0x60, 0x9b, 0x19, 0x27, 0x93, 0x6a, 0x9f, 0xc1, 0x07, 0xf0, 0x75, 0x25, 0x27,
	0x5f, 0xad, 0xe8, 0xdd, 0xfc, 0xff, 0xbf, 0xf3, 0xcd, 0xc0, 0x59, 0x9a, 0x5b, 0x65, 0x62, 0x6d,
	0x94, 0x55, 0xdc, 0xd1, 0x59, 0xf8, 0xcb, 0x01, 0x2f, 0x69, 0x3d, 0x2e, 0xe0, 0x84, 0xe0, 0xb2,
	0x10, 0x2c, 0x60, 0x91, 0x2b, 0x07, 0xc9, 0x1f, 0x80, 0x4f, 0xcf, 0x9b, 0x74, 0x8b, 0xc2, 0x09,
	0x58, 0xe4, 0xcb, 0xc9, 0xe0, 0xf7, 0x61, 0xb6, 0xc2, 0xaa, 0x40, 0x23, 0xdc, 0x80, 0x45, 0x9e,
	0xec, 0x15, 0x7f, 0x08, 0x40, 0x41, 0xd7, 0xb8, 0xc3, 0x8d, 0xb8, 0x4b, 0xec, 0xc0, 0x69, 0x79,
	0x6e, 0x30, 0xb5, 0xf8, 0xb9, 0xdc, 0xa2, 0xf0, 0xa8, 0xe5, 0x81, 0xc3, 0x2f, 0xe1, 0x94, 0xa2,
	0x17, 0x3f, 0xb5, 0x98, 0x11, 0x1d, 0x75, 0xcb, 0xd6, 0x98, 0x16, 0xcb, 0x5c, 0x55, 0xe2, 0x84,
	0x2a, 0x8f, 0xba, 0x65, 0xbb, 0x52, 0x77, 0x5d, 0x4f, 0x3b, 0x36, 0xe8, 0xb6, 0xe7, 0x6d, 0xb9,
	0x5a, 0xdb, 0x8f, 0xea, 0x07, 0x1a, 0xe1, 0x77, 0x3d, 0x27, 0x27, 0x7c, 0x03, 0xf7, 0xe8, 0x18,
	0x9f, 0x70, 0x83, 0xb9, 0x95, 0x58, 0x6b, 0x55, 0xd5, 0xc8, 0x9f, 0xf4, 0x07, 0xb8, 0x2e, 0x6b,
	0x2b, 0x58, 0xe0, 0x46, 0x67, 0xcf, 0xfd, 0x58, 0x67, 0x31, 0xc5, 0xca, 0x89, 0x85, 0xef, 0x81,
	0x93, 0x77, 0x45, 0x6b, 0x48, 0xfc, 0xde, 0x60, 0x6d, 0x8f, 0xef, 0xc7, 0xfe, 0x7f, 0x3f, 0xe7,
	0xf0, 0x7e, 0xe3, 0x2c, 0x43, 0xad, 0xbf, 0x66, 0x59, 0x56, 0xb7, 0x8a, 0x8a, 0xfd, 0x63, 0x96,
	0x96, 0x85, 0xbf, 0x59, 0x3f, 0xcc, 0xa2, 0xb2, 0x68, 0xc6, 0xfc, 0x2b, 0xf0, 0x57, 0x4d, 0x59,
	0xe0, 0x87, 0x54, 0xd7, 0xc2, 0xa1, 0x5d, 0x1e, 0x8d, 0xf9, 0x47, 0xa1, 0xf1, 0xbb, 0x21, 0x6e,
	0x51, 0x59, 0xb3, 0x97, 0x53, 0xde, 0xe5, 0x6b, 0x38, 0x3f, 0x86, 0x7c, 0x0e, 0xee, 0x37, 0xdc,
	0xd3, 0x40, 0x9e, 0x6c, 0x9f, 0xfc, 0x02, 0xbc, 0x5d, 0xba, 0x69, 0xb0, 0x5f, 0xab, 0x13, 0xaf,
	0x9c, 0x97, 0xec, 0xe9, 0x63, 0x38, 0xa7, 0x6e, 0x89, 0xb5, 0xa6, 0xcc, 0x1a, 0x8b, 0xfc, 0x02,
	0xe6, 0x49, 0xf2, 0x75, 0xd4, 0x37, 0xaa, 0xc2, 0xf9, 0x9d, 0xb7, 0xde, 0x17, 0xf7, 0x99, 0xce,
	0xb2, 0x19, 0xfd, 0xd6, 0x17, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x83, 0xf0, 0x77, 0x9d, 0xbc,
	0x02, 0x00, 0x00,
}
