// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: base_type.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type None struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *None) Reset()         { *m = None{} }
func (m *None) String() string { return proto.CompactTextString(m) }
func (*None) ProtoMessage()    {}
func (*None) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{0}
}
func (m *None) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_None.Unmarshal(m, b)
}
func (m *None) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_None.Marshal(b, m, deterministic)
}
func (m *None) XXX_Merge(src proto.Message) {
	xxx_messageInfo_None.Merge(m, src)
}
func (m *None) XXX_Size() int {
	return xxx_messageInfo_None.Size(m)
}
func (m *None) XXX_DiscardUnknown() {
	xxx_messageInfo_None.DiscardUnknown(m)
}

var xxx_messageInfo_None proto.InternalMessageInfo

type Bool struct {
	Value                bool     `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bool) Reset()         { *m = Bool{} }
func (m *Bool) String() string { return proto.CompactTextString(m) }
func (*Bool) ProtoMessage()    {}
func (*Bool) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{1}
}
func (m *Bool) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bool.Unmarshal(m, b)
}
func (m *Bool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bool.Marshal(b, m, deterministic)
}
func (m *Bool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bool.Merge(m, src)
}
func (m *Bool) XXX_Size() int {
	return xxx_messageInfo_Bool.Size(m)
}
func (m *Bool) XXX_DiscardUnknown() {
	xxx_messageInfo_Bool.DiscardUnknown(m)
}

var xxx_messageInfo_Bool proto.InternalMessageInfo

func (m *Bool) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type Int32 struct {
	Value                int32    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32) Reset()         { *m = Int32{} }
func (m *Int32) String() string { return proto.CompactTextString(m) }
func (*Int32) ProtoMessage()    {}
func (*Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{2}
}
func (m *Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32.Unmarshal(m, b)
}
func (m *Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32.Marshal(b, m, deterministic)
}
func (m *Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32.Merge(m, src)
}
func (m *Int32) XXX_Size() int {
	return xxx_messageInfo_Int32.Size(m)
}
func (m *Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int32 proto.InternalMessageInfo

func (m *Int32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64 struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64) Reset()         { *m = Int64{} }
func (m *Int64) String() string { return proto.CompactTextString(m) }
func (*Int64) ProtoMessage()    {}
func (*Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{3}
}
func (m *Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64.Unmarshal(m, b)
}
func (m *Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64.Marshal(b, m, deterministic)
}
func (m *Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64.Merge(m, src)
}
func (m *Int64) XXX_Size() int {
	return xxx_messageInfo_Int64.Size(m)
}
func (m *Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64 proto.InternalMessageInfo

func (m *Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Double struct {
	Value                float64  `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Double) Reset()         { *m = Double{} }
func (m *Double) String() string { return proto.CompactTextString(m) }
func (*Double) ProtoMessage()    {}
func (*Double) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{4}
}
func (m *Double) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Double.Unmarshal(m, b)
}
func (m *Double) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Double.Marshal(b, m, deterministic)
}
func (m *Double) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Double.Merge(m, src)
}
func (m *Double) XXX_Size() int {
	return xxx_messageInfo_Double.Size(m)
}
func (m *Double) XXX_DiscardUnknown() {
	xxx_messageInfo_Double.DiscardUnknown(m)
}

var xxx_messageInfo_Double proto.InternalMessageInfo

func (m *Double) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type String struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *String) Reset()         { *m = String{} }
func (m *String) String() string { return proto.CompactTextString(m) }
func (*String) ProtoMessage()    {}
func (*String) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{5}
}
func (m *String) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_String.Unmarshal(m, b)
}
func (m *String) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_String.Marshal(b, m, deterministic)
}
func (m *String) XXX_Merge(src proto.Message) {
	xxx_messageInfo_String.Merge(m, src)
}
func (m *String) XXX_Size() int {
	return xxx_messageInfo_String.Size(m)
}
func (m *String) XXX_DiscardUnknown() {
	xxx_messageInfo_String.DiscardUnknown(m)
}

var xxx_messageInfo_String proto.InternalMessageInfo

func (m *String) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Int64Int32 struct {
	Key                  int64    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Int32) Reset()         { *m = Int64Int32{} }
func (m *Int64Int32) String() string { return proto.CompactTextString(m) }
func (*Int64Int32) ProtoMessage()    {}
func (*Int64Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{6}
}
func (m *Int64Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Int32.Unmarshal(m, b)
}
func (m *Int64Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Int32.Marshal(b, m, deterministic)
}
func (m *Int64Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Int32.Merge(m, src)
}
func (m *Int64Int32) XXX_Size() int {
	return xxx_messageInfo_Int64Int32.Size(m)
}
func (m *Int64Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Int32 proto.InternalMessageInfo

func (m *Int64Int32) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Int64Int32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int64Int64 struct {
	Key                  int64    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64Int64) Reset()         { *m = Int64Int64{} }
func (m *Int64Int64) String() string { return proto.CompactTextString(m) }
func (*Int64Int64) ProtoMessage()    {}
func (*Int64Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{7}
}
func (m *Int64Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64Int64.Unmarshal(m, b)
}
func (m *Int64Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64Int64.Marshal(b, m, deterministic)
}
func (m *Int64Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64Int64.Merge(m, src)
}
func (m *Int64Int64) XXX_Size() int {
	return xxx_messageInfo_Int64Int64.Size(m)
}
func (m *Int64Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int64Int64 proto.InternalMessageInfo

func (m *Int64Int64) GetKey() int64 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Int64Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int32Int32 struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int32    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Int32) Reset()         { *m = Int32Int32{} }
func (m *Int32Int32) String() string { return proto.CompactTextString(m) }
func (*Int32Int32) ProtoMessage()    {}
func (*Int32Int32) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{8}
}
func (m *Int32Int32) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Int32.Unmarshal(m, b)
}
func (m *Int32Int32) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Int32.Marshal(b, m, deterministic)
}
func (m *Int32Int32) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Int32.Merge(m, src)
}
func (m *Int32Int32) XXX_Size() int {
	return xxx_messageInfo_Int32Int32.Size(m)
}
func (m *Int32Int32) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Int32.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Int32 proto.InternalMessageInfo

func (m *Int32Int32) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Int32Int32) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int32Int64 struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                int64    `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32Int64) Reset()         { *m = Int32Int64{} }
func (m *Int32Int64) String() string { return proto.CompactTextString(m) }
func (*Int32Int64) ProtoMessage()    {}
func (*Int32Int64) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{9}
}
func (m *Int32Int64) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Int64.Unmarshal(m, b)
}
func (m *Int32Int64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Int64.Marshal(b, m, deterministic)
}
func (m *Int32Int64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Int64.Merge(m, src)
}
func (m *Int32Int64) XXX_Size() int {
	return xxx_messageInfo_Int32Int64.Size(m)
}
func (m *Int32Int64) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Int64.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Int64 proto.InternalMessageInfo

func (m *Int32Int64) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *Int32Int64) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Int32List struct {
	List                 []int32  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int32List) Reset()         { *m = Int32List{} }
func (m *Int32List) String() string { return proto.CompactTextString(m) }
func (*Int32List) ProtoMessage()    {}
func (*Int32List) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{10}
}
func (m *Int32List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32List.Unmarshal(m, b)
}
func (m *Int32List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32List.Marshal(b, m, deterministic)
}
func (m *Int32List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32List.Merge(m, src)
}
func (m *Int32List) XXX_Size() int {
	return xxx_messageInfo_Int32List.Size(m)
}
func (m *Int32List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32List.DiscardUnknown(m)
}

var xxx_messageInfo_Int32List proto.InternalMessageInfo

func (m *Int32List) GetList() []int32 {
	if m != nil {
		return m.List
	}
	return nil
}

type Int64List struct {
	List                 []int64  `protobuf:"varint,1,rep,packed,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Int64List) Reset()         { *m = Int64List{} }
func (m *Int64List) String() string { return proto.CompactTextString(m) }
func (*Int64List) ProtoMessage()    {}
func (*Int64List) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{11}
}
func (m *Int64List) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int64List.Unmarshal(m, b)
}
func (m *Int64List) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int64List.Marshal(b, m, deterministic)
}
func (m *Int64List) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int64List.Merge(m, src)
}
func (m *Int64List) XXX_Size() int {
	return xxx_messageInfo_Int64List.Size(m)
}
func (m *Int64List) XXX_DiscardUnknown() {
	xxx_messageInfo_Int64List.DiscardUnknown(m)
}

var xxx_messageInfo_Int64List proto.InternalMessageInfo

func (m *Int64List) GetList() []int64 {
	if m != nil {
		return m.List
	}
	return nil
}

type Int32Map struct {
	Value                map[int32]int32 `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Int32Map) Reset()         { *m = Int32Map{} }
func (m *Int32Map) String() string { return proto.CompactTextString(m) }
func (*Int32Map) ProtoMessage()    {}
func (*Int32Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{12}
}
func (m *Int32Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Map.Unmarshal(m, b)
}
func (m *Int32Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Map.Marshal(b, m, deterministic)
}
func (m *Int32Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Map.Merge(m, src)
}
func (m *Int32Map) XXX_Size() int {
	return xxx_messageInfo_Int32Map.Size(m)
}
func (m *Int32Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Map.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Map proto.InternalMessageInfo

func (m *Int32Map) GetValue() map[int32]int32 {
	if m != nil {
		return m.Value
	}
	return nil
}

type Int32Int64Map struct {
	Value                map[int32]int64 `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Int32Int64Map) Reset()         { *m = Int32Int64Map{} }
func (m *Int32Int64Map) String() string { return proto.CompactTextString(m) }
func (*Int32Int64Map) ProtoMessage()    {}
func (*Int32Int64Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_97d27fbb7286dd8c, []int{13}
}
func (m *Int32Int64Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Int32Int64Map.Unmarshal(m, b)
}
func (m *Int32Int64Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Int32Int64Map.Marshal(b, m, deterministic)
}
func (m *Int32Int64Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Int32Int64Map.Merge(m, src)
}
func (m *Int32Int64Map) XXX_Size() int {
	return xxx_messageInfo_Int32Int64Map.Size(m)
}
func (m *Int32Int64Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Int32Int64Map.DiscardUnknown(m)
}

var xxx_messageInfo_Int32Int64Map proto.InternalMessageInfo

func (m *Int32Int64Map) GetValue() map[int32]int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*None)(nil), "pb.None")
	proto.RegisterType((*Bool)(nil), "pb.Bool")
	proto.RegisterType((*Int32)(nil), "pb.Int32")
	proto.RegisterType((*Int64)(nil), "pb.Int64")
	proto.RegisterType((*Double)(nil), "pb.Double")
	proto.RegisterType((*String)(nil), "pb.String")
	proto.RegisterType((*Int64Int32)(nil), "pb.Int64Int32")
	proto.RegisterType((*Int64Int64)(nil), "pb.Int64Int64")
	proto.RegisterType((*Int32Int32)(nil), "pb.Int32Int32")
	proto.RegisterType((*Int32Int64)(nil), "pb.Int32Int64")
	proto.RegisterType((*Int32List)(nil), "pb.Int32List")
	proto.RegisterType((*Int64List)(nil), "pb.Int64List")
	proto.RegisterType((*Int32Map)(nil), "pb.Int32Map")
	proto.RegisterMapType((map[int32]int32)(nil), "pb.Int32Map.ValueEntry")
	proto.RegisterType((*Int32Int64Map)(nil), "pb.Int32Int64Map")
	proto.RegisterMapType((map[int32]int64)(nil), "pb.Int32Int64Map.ValueEntry")
}

func init() { proto.RegisterFile("base_type.proto", fileDescriptor_97d27fbb7286dd8c) }

var fileDescriptor_97d27fbb7286dd8c = []byte{
	// 286 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4b, 0x84, 0x40,
	0x14, 0xc6, 0x19, 0xc7, 0x91, 0xdd, 0x17, 0x51, 0x0c, 0x41, 0x4b, 0x6c, 0xb5, 0x78, 0xf2, 0x92,
	0x81, 0x8a, 0x2c, 0x1d, 0x97, 0x3a, 0x04, 0xd5, 0x61, 0x83, 0x0e, 0x5d, 0xc2, 0x81, 0x21, 0x24,
	0x71, 0x06, 0x9d, 0x0d, 0x3c, 0xf4, 0xbf, 0x87, 0xb3, 0x9a, 0x3e, 0x16, 0xda, 0xa0, 0xdb, 0xe8,
	0xef, 0xfb, 0xe6, 0xf7, 0x9e, 0x08, 0x47, 0x22, 0xab, 0xe5, 0x9b, 0x69, 0xb4, 0x0c, 0x75, 0xa5,
	0x8c, 0xe2, 0x8e, 0x16, 0xbe, 0x07, 0xee, 0x93, 0x2a, 0xa5, 0x3f, 0x07, 0x77, 0xa5, 0x54, 0xc1,
	0x4f, 0x80, 0x7d, 0x66, 0xc5, 0x46, 0xce, 0xc8, 0x82, 0x04, 0x93, 0xf5, 0xf6, 0xc1, 0x3f, 0x07,
	0x76, 0x5f, 0x9a, 0x38, 0xc2, 0x98, 0x61, 0x9c, 0x26, 0x18, 0xd3, 0x1e, 0x5f, 0x80, 0x77, 0xab,
	0x36, 0xa2, 0x90, 0x98, 0x93, 0x11, 0x7f, 0x36, 0x55, 0x5e, 0xbe, 0x63, 0x3e, 0xed, 0x79, 0x02,
	0x60, 0xaf, 0xdf, 0x8e, 0x70, 0x0c, 0xf4, 0x43, 0x36, 0x9d, 0xa1, 0x3d, 0x0e, 0x2d, 0x67, 0x3c,
	0xd4, 0xa8, 0x95, 0x26, 0xfb, 0x5a, 0x14, 0xb7, 0xe2, 0x68, 0xc7, 0xc5, 0xf6, 0xbb, 0x6c, 0x0b,
	0xbb, 0xd8, 0x6f, 0xae, 0x4b, 0x98, 0xda, 0xd6, 0x43, 0x5e, 0x1b, 0xce, 0xc1, 0x2d, 0xf2, 0xda,
	0xcc, 0xc8, 0x82, 0x06, 0x6c, 0x6d, 0xcf, 0x5d, 0x20, 0x4d, 0x76, 0x02, 0xb4, 0x0b, 0xd4, 0x30,
	0xb1, 0x37, 0x3c, 0x66, 0x9a, 0x5f, 0x0d, 0xdf, 0x8e, 0x06, 0x07, 0xd1, 0x69, 0xa8, 0x45, 0xd8,
	0xc3, 0xf0, 0xa5, 0x25, 0x77, 0xa5, 0xa9, 0x9a, 0x4e, 0x7e, 0xb6, 0x04, 0x18, 0x5e, 0xfe, 0x75,
	0xd1, 0x1b, 0x67, 0x49, 0xfc, 0x2f, 0x38, 0x1c, 0x96, 0x6d, 0xcd, 0x11, 0x36, 0xcf, 0x7f, 0xcc,
	0x7d, 0xe2, 0xbf, 0x7a, 0x3a, 0xd2, 0xaf, 0xd8, 0x2b, 0xbd, 0xd6, 0x42, 0x78, 0xf6, 0x1f, 0x8e,
	0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x73, 0x95, 0x78, 0xc1, 0xd6, 0x02, 0x00, 0x00,
}
