// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpc.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 节点状态
type NodeState int32

const (
	NodeState_Open     NodeState = 0
	NodeState_Maintain NodeState = 1
	NodeState_Closed   NodeState = 2
)

var NodeState_name = map[int32]string{
	0: "Open",
	1: "Maintain",
	2: "Closed",
}

var NodeState_value = map[string]int32{
	"Open":     0,
	"Maintain": 1,
	"Closed":   2,
}

func (x NodeState) String() string {
	return proto.EnumName(NodeState_name, int32(x))
}

func (NodeState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

// 注册开发帐号
type DevRegister struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevRegister) Reset()         { *m = DevRegister{} }
func (m *DevRegister) String() string { return proto.CompactTextString(m) }
func (*DevRegister) ProtoMessage()    {}
func (*DevRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}
func (m *DevRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevRegister.Unmarshal(m, b)
}
func (m *DevRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevRegister.Marshal(b, m, deterministic)
}
func (m *DevRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevRegister.Merge(m, src)
}
func (m *DevRegister) XXX_Size() int {
	return xxx_messageInfo_DevRegister.Size(m)
}
func (m *DevRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_DevRegister.DiscardUnknown(m)
}

var xxx_messageInfo_DevRegister proto.InternalMessageInfo

func (m *DevRegister) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *DevRegister) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DevRegister) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

// 用户信息
type User struct {
	SdkId                int32    `protobuf:"varint,1,opt,name=sdkId,proto3" json:"sdkId,omitempty"`
	Pid                  int32    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	OpenId               string   `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`
	ServerId             int32    `protobuf:"varint,4,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Uid                  int64    `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Ip                   string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetSdkId() int32 {
	if m != nil {
		return m.SdkId
	}
	return 0
}

func (m *User) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *User) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *User) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *User) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *User) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func init() {
	proto.RegisterEnum("cherry.proto.pb.NodeState", NodeState_name, NodeState_value)
	proto.RegisterType((*DevRegister)(nil), "cherry.proto.pb.DevRegister")
	proto.RegisterType((*User)(nil), "cherry.proto.pb.User")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x85, 0xed, 0x2f, 0xed, 0x1d, 0xd1, 0x72, 0x11, 0x29, 0xae, 0xca, 0xac, 0x06, 0x17, 0x33,
	0x0b, 0xdf, 0x40, 0xdd, 0x74, 0xe1, 0x08, 0x15, 0x37, 0xba, 0x4a, 0x9b, 0x8b, 0x06, 0x35, 0xb9,
	0x24, 0x99, 0x11, 0xf7, 0x3e, 0xb8, 0x34, 0xad, 0xc3, 0xec, 0xce, 0x77, 0x12, 0xbe, 0x1c, 0x02,
	0xa5, 0xe5, 0x61, 0xcd, 0xd6, 0x78, 0x83, 0xe7, 0xc3, 0x3b, 0x59, 0xfb, 0x33, 0xd1, 0x9a, 0xfb,
	0xe5, 0x2b, 0x2c, 0xee, 0x69, 0xdf, 0xd1, 0x9b, 0x72, 0x9e, 0x2c, 0x36, 0xb0, 0x10, 0xc3, 0x60,
	0x76, 0xda, 0x6f, 0xc5, 0x17, 0xd5, 0x51, 0x13, 0xad, 0xca, 0xee, 0xb8, 0xc2, 0x2b, 0x28, 0x58,
	0x38, 0xf7, 0x6d, 0xac, 0xac, 0xe3, 0x70, 0x7c, 0x60, 0x3c, 0x83, 0x58, 0x71, 0x9d, 0x84, 0x36,
	0x56, 0xbc, 0xfc, 0x8d, 0x20, 0x7d, 0x76, 0x64, 0xf1, 0x02, 0x32, 0x27, 0x3f, 0x5a, 0x19, 0x84,
	0x59, 0x37, 0x01, 0x56, 0x90, 0xb0, 0x9a, 0x2c, 0x59, 0x37, 0x46, 0xbc, 0x84, 0xdc, 0x30, 0xe9,
	0x56, 0xce, 0x92, 0x99, 0xc6, 0x47, 0x1d, 0xd9, 0x3d, 0xd9, 0x56, 0xd6, 0x69, 0xb8, 0x7e, 0xe0,
	0xd1, 0xb2, 0x53, 0xb2, 0xce, 0x9a, 0x68, 0x95, 0x74, 0x63, 0x9c, 0x67, 0xe4, 0xff, 0x33, 0xae,
	0x37, 0x50, 0x6e, 0x8d, 0xa4, 0x27, 0x2f, 0x3c, 0x61, 0x01, 0xe9, 0x23, 0x93, 0xae, 0x4e, 0xf0,
	0x14, 0x8a, 0x07, 0xa1, 0xb4, 0x17, 0x4a, 0x57, 0x11, 0x02, 0xe4, 0x77, 0x9f, 0xc6, 0x91, 0xac,
	0xe2, 0xdb, 0xec, 0x25, 0xd9, 0x70, 0xdf, 0xe7, 0xe1, 0x97, 0x6e, 0xfe, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x49, 0xbd, 0xd2, 0x0a, 0x40, 0x01, 0x00, 0x00,
}
