// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: login.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// 登陆请求(建立连接后的第一条消息，验证通过后则进行后续流程)
type LoginRequest struct {
	ServerId             int32            `protobuf:"varint,1,opt,name=serverId,proto3" json:"serverId,omitempty"`
	Token                string           `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Params               map[int32]string `protobuf:"bytes,5,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}
func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetServerId() int32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRequest) GetParams() map[int32]string {
	if m != nil {
		return m.Params
	}
	return nil
}

// 登陆响应
type LoginResponse struct {
	Uid                  int64            `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Pid                  int32            `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	OpenId               string           `protobuf:"bytes,3,opt,name=openId,proto3" json:"openId,omitempty"`
	Params               map[int32]string `protobuf:"bytes,4,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LoginResponse) GetPid() int32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *LoginResponse) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *LoginResponse) GetParams() map[int32]string {
	if m != nil {
		return m.Params
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "pb.LoginRequest")
	proto.RegisterMapType((map[int32]string)(nil), "pb.LoginRequest.ParamsEntry")
	proto.RegisterType((*LoginResponse)(nil), "pb.LoginResponse")
	proto.RegisterMapType((map[int32]string)(nil), "pb.LoginResponse.ParamsEntry")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xda, 0xc8, 0xc8, 0xc5,
	0xe3, 0x03, 0x12, 0x0b, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x92, 0xe2, 0xe2, 0x28, 0x4e,
	0x2d, 0x2a, 0x4b, 0x2d, 0xf2, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0xf3, 0x85,
	0x44, 0xb8, 0x58, 0x4b, 0xf2, 0xb3, 0x53, 0xf3, 0x24, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20,
	0x1c, 0x21, 0x13, 0x2e, 0xb6, 0x82, 0xc4, 0xa2, 0xc4, 0xdc, 0x62, 0x09, 0x56, 0x05, 0x66, 0x0d,
	0x6e, 0x23, 0x19, 0xbd, 0x82, 0x24, 0x3d, 0x64, 0x33, 0xf5, 0x02, 0xc0, 0xd2, 0xae, 0x79, 0x25,
	0x45, 0x95, 0x41, 0x50, 0xb5, 0x52, 0x96, 0x5c, 0xdc, 0x48, 0xc2, 0x42, 0x02, 0x5c, 0xcc, 0xd9,
	0xa9, 0x95, 0x50, 0x1b, 0x41, 0x4c, 0x90, 0x65, 0x65, 0x89, 0x39, 0xa5, 0xa9, 0x30, 0xcb, 0xc0,
	0x1c, 0x2b, 0x26, 0x0b, 0x46, 0xa5, 0xbd, 0x8c, 0x5c, 0xbc, 0x50, 0xf3, 0x8b, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x41, 0xba, 0x4b, 0x33, 0x21, 0xee, 0x65, 0x0e, 0x02, 0x31, 0x41, 0x22, 0x05, 0x99,
	0x29, 0x60, 0xbd, 0xac, 0x41, 0x20, 0xa6, 0x90, 0x18, 0x17, 0x5b, 0x7e, 0x41, 0x6a, 0x9e, 0x67,
	0x8a, 0x04, 0x33, 0xd8, 0x40, 0x28, 0x4f, 0xc8, 0x14, 0xee, 0x7c, 0x16, 0xb0, 0xf3, 0x65, 0x91,
	0x9c, 0x0f, 0x31, 0x9e, 0xca, 0xee, 0x77, 0x62, 0x8d, 0x62, 0xd6, 0x2f, 0x48, 0x4a, 0x62, 0x03,
	0xc7, 0x82, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x8e, 0x30, 0x59, 0x94, 0x01, 0x00, 0x00,
}
